spotPython.fun.hyperlight 2024-01-07 23:03:04,301 INFO Starting the logger at level 10 for module spotPython.fun.hyperlight:
spotPython.fun.hyperlight 2024-01-07 23:03:04,342 DEBUG 
config: {'l1': 32, 'epochs': 1024, 'batch_size': 32, 'act_fn': ReLU(), 'optimizer': 'Adadelta', 'dropout_prob': 0.16159096025710312, 'lr_mult': 4.5111856050890955, 'patience': 32, 'initialization': 'Kaiming'}
spotPython.fun.hyperlight 2024-01-07 23:03:04,342 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-07 23:03:04,343 ERROR Error in fun(). Call to train_model failed. err=IndexError('tuple index out of range'), type(err)=<class 'IndexError'>
spotPython.fun.hyperlight 2024-01-07 23:03:04,343 ERROR Setting df_eval to np.nan
spotPython.fun.hyperlight 2024-01-07 23:03:04,344 DEBUG 
config: {'l1': 32, 'epochs': 1024, 'batch_size': 32, 'act_fn': ReLU(), 'optimizer': 'Adadelta', 'dropout_prob': 0.1777825780149944, 'lr_mult': 4.708937024088116, 'patience': 128, 'initialization': 'Default'}
spotPython.fun.hyperlight 2024-01-07 23:03:04,344 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-07 23:04:01,057 DEBUG fun: train_model returned
spotPython.fun.hyperlight 2024-01-07 23:04:01,058 DEBUG 
config: {'l1': 32, 'epochs': 2048, 'batch_size': 32, 'act_fn': ReLU(), 'optimizer': 'Adadelta', 'dropout_prob': 0.03853826903187715, 'lr_mult': 4.2070303361561034, 'patience': 32, 'initialization': 'Kaiming'}
spotPython.fun.hyperlight 2024-01-07 23:04:01,058 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-07 23:04:01,058 ERROR Error in fun(). Call to train_model failed. err=IndexError('tuple index out of range'), type(err)=<class 'IndexError'>
spotPython.fun.hyperlight 2024-01-07 23:04:01,058 ERROR Setting df_eval to np.nan
spotPython.fun.hyperlight 2024-01-07 23:04:01,058 DEBUG 
config: {'l1': 32, 'epochs': 1024, 'batch_size': 32, 'act_fn': ReLU(), 'optimizer': 'Adadelta', 'dropout_prob': 0.04855170483520874, 'lr_mult': 4.270723672455743, 'patience': 64, 'initialization': 'Default'}
spotPython.fun.hyperlight 2024-01-07 23:04:01,058 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-07 23:04:41,639 DEBUG fun: train_model returned
spotPython.fun.hyperlight 2024-01-07 23:04:41,639 DEBUG 
config: {'l1': 32, 'epochs': 2048, 'batch_size': 32, 'act_fn': ReLU(), 'optimizer': 'Adadelta', 'dropout_prob': 0.023939129651370343, 'lr_mult': 4.860088441260088, 'patience': 64, 'initialization': 'Kaiming'}
spotPython.fun.hyperlight 2024-01-07 23:04:41,639 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-07 23:04:41,640 ERROR Error in fun(). Call to train_model failed. err=IndexError('tuple index out of range'), type(err)=<class 'IndexError'>
spotPython.fun.hyperlight 2024-01-07 23:04:41,640 ERROR Setting df_eval to np.nan
spotPython.fun.hyperlight 2024-01-07 23:04:41,640 DEBUG 
config: {'l1': 32, 'epochs': 1024, 'batch_size': 32, 'act_fn': ReLU(), 'optimizer': 'Adadelta', 'dropout_prob': 0.07481938746043248, 'lr_mult': 4.53087026687267, 'patience': 128, 'initialization': 'Xavier'}
spotPython.fun.hyperlight 2024-01-07 23:04:41,640 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-07 23:04:41,640 ERROR Error in fun(). Call to train_model failed. err=IndexError('tuple index out of range'), type(err)=<class 'IndexError'>
spotPython.fun.hyperlight 2024-01-07 23:04:41,640 ERROR Setting df_eval to np.nan
spotPython.fun.hyperlight 2024-01-07 23:04:41,640 DEBUG 
config: {'l1': 32, 'epochs': 2048, 'batch_size': 32, 'act_fn': ReLU(), 'optimizer': 'Adadelta', 'dropout_prob': 0.08702835409168731, 'lr_mult': 4.75127428507, 'patience': 32, 'initialization': 'Kaiming'}
spotPython.fun.hyperlight 2024-01-07 23:04:41,640 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-07 23:04:41,641 ERROR Error in fun(). Call to train_model failed. err=IndexError('tuple index out of range'), type(err)=<class 'IndexError'>
spotPython.fun.hyperlight 2024-01-07 23:04:41,641 ERROR Setting df_eval to np.nan
spotPython.fun.hyperlight 2024-01-07 23:04:41,641 DEBUG 
config: {'l1': 32, 'epochs': 2048, 'batch_size': 32, 'act_fn': ReLU(), 'optimizer': 'Adadelta', 'dropout_prob': 0.06474246899580567, 'lr_mult': 4.045391131486251, 'patience': 64, 'initialization': 'Xavier'}
spotPython.fun.hyperlight 2024-01-07 23:04:41,641 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-07 23:04:41,641 ERROR Error in fun(). Call to train_model failed. err=IndexError('tuple index out of range'), type(err)=<class 'IndexError'>
spotPython.fun.hyperlight 2024-01-07 23:04:41,641 ERROR Setting df_eval to np.nan
spotPython.fun.hyperlight 2024-01-07 23:04:41,641 DEBUG 
config: {'l1': 32, 'epochs': 2048, 'batch_size': 32, 'act_fn': ReLU(), 'optimizer': 'Adadelta', 'dropout_prob': 0.19556738808285198, 'lr_mult': 4.390483744014816, 'patience': 32, 'initialization': 'Kaiming'}
spotPython.fun.hyperlight 2024-01-07 23:04:41,642 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-07 23:04:41,642 ERROR Error in fun(). Call to train_model failed. err=IndexError('tuple index out of range'), type(err)=<class 'IndexError'>
spotPython.fun.hyperlight 2024-01-07 23:04:41,642 ERROR Setting df_eval to np.nan
spotPython.fun.hyperlight 2024-01-07 23:04:41,642 DEBUG 
config: {'l1': 32, 'epochs': 1024, 'batch_size': 32, 'act_fn': ReLU(), 'optimizer': 'Adadelta', 'dropout_prob': 0.0478899939763955, 'lr_mult': 4.958697923135737, 'patience': 64, 'initialization': 'Kaiming'}
spotPython.fun.hyperlight 2024-01-07 23:04:41,642 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-07 23:04:41,642 ERROR Error in fun(). Call to train_model failed. err=IndexError('tuple index out of range'), type(err)=<class 'IndexError'>
spotPython.fun.hyperlight 2024-01-07 23:04:41,642 ERROR Setting df_eval to np.nan
spotPython.fun.hyperlight 2024-01-07 23:04:41,643 DEBUG 
config: {'l1': 32, 'epochs': 1024, 'batch_size': 32, 'act_fn': ReLU(), 'optimizer': 'Adadelta', 'dropout_prob': 0.09924252496268761, 'lr_mult': 4.919872755628267, 'patience': 64, 'initialization': 'Kaiming'}
spotPython.fun.hyperlight 2024-01-07 23:04:41,643 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-07 23:04:41,643 ERROR Error in fun(). Call to train_model failed. err=IndexError('tuple index out of range'), type(err)=<class 'IndexError'>
spotPython.fun.hyperlight 2024-01-07 23:04:41,643 ERROR Setting df_eval to np.nan
spotPython.fun.hyperlight 2024-01-07 23:04:41,643 DEBUG 
config: {'l1': 32, 'epochs': 2048, 'batch_size': 32, 'act_fn': ReLU(), 'optimizer': 'Adadelta', 'dropout_prob': 0.1404532221604549, 'lr_mult': 4.615340349943592, 'patience': 64, 'initialization': 'Default'}
spotPython.fun.hyperlight 2024-01-07 23:04:41,643 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-07 23:05:29,757 DEBUG fun: train_model returned
spotPython.fun.hyperlight 2024-01-07 23:05:29,757 DEBUG 
config: {'l1': 32, 'epochs': 2048, 'batch_size': 32, 'act_fn': ReLU(), 'optimizer': 'Adadelta', 'dropout_prob': 0.1030330415603706, 'lr_mult': 4.297356436546931, 'patience': 128, 'initialization': 'Default'}
spotPython.fun.hyperlight 2024-01-07 23:05:29,757 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-07 23:06:24,937 DEBUG fun: train_model returned
spotPython.fun.hyperlight 2024-01-07 23:06:24,938 DEBUG 
config: {'l1': 32, 'epochs': 2048, 'batch_size': 32, 'act_fn': ReLU(), 'optimizer': 'Adadelta', 'dropout_prob': 0.014032934009923484, 'lr_mult': 4.015057663913676, 'patience': 32, 'initialization': 'Xavier'}
spotPython.fun.hyperlight 2024-01-07 23:06:24,938 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-07 23:06:24,938 ERROR Error in fun(). Call to train_model failed. err=IndexError('tuple index out of range'), type(err)=<class 'IndexError'>
spotPython.fun.hyperlight 2024-01-07 23:06:24,938 ERROR Setting df_eval to np.nan
spotPython.fun.hyperlight 2024-01-07 23:06:24,938 DEBUG 
config: {'l1': 32, 'epochs': 1024, 'batch_size': 32, 'act_fn': ReLU(), 'optimizer': 'Adadelta', 'dropout_prob': 0.08205472490575583, 'lr_mult': 4.343656360800315, 'patience': 64, 'initialization': 'Kaiming'}
spotPython.fun.hyperlight 2024-01-07 23:06:24,938 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-07 23:06:24,939 ERROR Error in fun(). Call to train_model failed. err=IndexError('tuple index out of range'), type(err)=<class 'IndexError'>
spotPython.fun.hyperlight 2024-01-07 23:06:24,939 ERROR Setting df_eval to np.nan
spotPython.fun.hyperlight 2024-01-07 23:06:24,939 DEBUG 
config: {'l1': 32, 'epochs': 2048, 'batch_size': 32, 'act_fn': ReLU(), 'optimizer': 'Adadelta', 'dropout_prob': 0.17256289930490684, 'lr_mult': 4.450244835707213, 'patience': 64, 'initialization': 'Kaiming'}
spotPython.fun.hyperlight 2024-01-07 23:06:24,939 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-07 23:06:24,939 ERROR Error in fun(). Call to train_model failed. err=IndexError('tuple index out of range'), type(err)=<class 'IndexError'>
spotPython.fun.hyperlight 2024-01-07 23:06:24,939 ERROR Setting df_eval to np.nan
spotPython.fun.hyperlight 2024-01-07 23:06:24,939 DEBUG 
config: {'l1': 32, 'epochs': 1024, 'batch_size': 32, 'act_fn': ReLU(), 'optimizer': 'Adadelta', 'dropout_prob': 0.057450759826890734, 'lr_mult': 4.196896961192057, 'patience': 64, 'initialization': 'Kaiming'}
spotPython.fun.hyperlight 2024-01-07 23:06:24,939 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-07 23:06:24,940 ERROR Error in fun(). Call to train_model failed. err=IndexError('tuple index out of range'), type(err)=<class 'IndexError'>
spotPython.fun.hyperlight 2024-01-07 23:06:24,940 ERROR Setting df_eval to np.nan
spotPython.fun.hyperlight 2024-01-07 23:06:24,940 DEBUG 
config: {'l1': 32, 'epochs': 1024, 'batch_size': 32, 'act_fn': ReLU(), 'optimizer': 'Adadelta', 'dropout_prob': 0.02557638344689936, 'lr_mult': 4.427245016850625, 'patience': 64, 'initialization': 'Kaiming'}
spotPython.fun.hyperlight 2024-01-07 23:06:24,940 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-07 23:06:24,940 ERROR Error in fun(). Call to train_model failed. err=IndexError('tuple index out of range'), type(err)=<class 'IndexError'>
spotPython.fun.hyperlight 2024-01-07 23:06:24,940 ERROR Setting df_eval to np.nan
spotPython.fun.hyperlight 2024-01-07 23:06:24,940 DEBUG 
config: {'l1': 32, 'epochs': 2048, 'batch_size': 32, 'act_fn': ReLU(), 'optimizer': 'Adadelta', 'dropout_prob': 0.14832878865475074, 'lr_mult': 4.773788592919557, 'patience': 128, 'initialization': 'Xavier'}
spotPython.fun.hyperlight 2024-01-07 23:06:24,940 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-07 23:06:24,941 ERROR Error in fun(). Call to train_model failed. err=IndexError('tuple index out of range'), type(err)=<class 'IndexError'>
spotPython.fun.hyperlight 2024-01-07 23:06:24,941 ERROR Setting df_eval to np.nan
spotPython.fun.hyperlight 2024-01-07 23:06:24,941 DEBUG 
config: {'l1': 32, 'epochs': 1024, 'batch_size': 32, 'act_fn': ReLU(), 'optimizer': 'Adadelta', 'dropout_prob': 0.11524830547705328, 'lr_mult': 4.645069082048478, 'patience': 128, 'initialization': 'Xavier'}
spotPython.fun.hyperlight 2024-01-07 23:06:24,941 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-07 23:06:24,941 ERROR Error in fun(). Call to train_model failed. err=IndexError('tuple index out of range'), type(err)=<class 'IndexError'>
spotPython.fun.hyperlight 2024-01-07 23:06:24,941 ERROR Setting df_eval to np.nan
spotPython.fun.hyperlight 2024-01-07 23:06:24,941 DEBUG 
config: {'l1': 32, 'epochs': 2048, 'batch_size': 32, 'act_fn': ReLU(), 'optimizer': 'Adadelta', 'dropout_prob': 0.16634107247452468, 'lr_mult': 4.8056561031376255, 'patience': 32, 'initialization': 'Xavier'}
spotPython.fun.hyperlight 2024-01-07 23:06:24,941 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-07 23:06:24,942 ERROR Error in fun(). Call to train_model failed. err=IndexError('tuple index out of range'), type(err)=<class 'IndexError'>
spotPython.fun.hyperlight 2024-01-07 23:06:24,942 ERROR Setting df_eval to np.nan
spotPython.fun.hyperlight 2024-01-07 23:06:24,942 DEBUG 
config: {'l1': 32, 'epochs': 1024, 'batch_size': 32, 'act_fn': ReLU(), 'optimizer': 'Adadelta', 'dropout_prob': 0.13212379694295062, 'lr_mult': 4.989527959116383, 'patience': 32, 'initialization': 'Xavier'}
spotPython.fun.hyperlight 2024-01-07 23:06:24,942 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-07 23:06:24,942 ERROR Error in fun(). Call to train_model failed. err=IndexError('tuple index out of range'), type(err)=<class 'IndexError'>
spotPython.fun.hyperlight 2024-01-07 23:06:24,942 ERROR Setting df_eval to np.nan
spotPython.fun.hyperlight 2024-01-07 23:06:24,942 DEBUG 
config: {'l1': 32, 'epochs': 2048, 'batch_size': 32, 'act_fn': ReLU(), 'optimizer': 'Adadelta', 'dropout_prob': 0.19017182224903995, 'lr_mult': 4.590250195817184, 'patience': 128, 'initialization': 'Kaiming'}
spotPython.fun.hyperlight 2024-01-07 23:06:24,942 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-07 23:06:24,943 ERROR Error in fun(). Call to train_model failed. err=IndexError('tuple index out of range'), type(err)=<class 'IndexError'>
spotPython.fun.hyperlight 2024-01-07 23:06:24,943 ERROR Setting df_eval to np.nan
spotPython.fun.hyperlight 2024-01-07 23:06:24,943 DEBUG 
config: {'l1': 32, 'epochs': 2048, 'batch_size': 32, 'act_fn': ReLU(), 'optimizer': 'Adadelta', 'dropout_prob': 0.11934392329418204, 'lr_mult': 4.098211383992335, 'patience': 64, 'initialization': 'Default'}
spotPython.fun.hyperlight 2024-01-07 23:06:24,943 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-07 23:07:14,003 DEBUG fun: train_model returned
spotPython.fun.hyperlight 2024-01-07 23:07:14,003 DEBUG 
config: {'l1': 32, 'epochs': 1024, 'batch_size': 32, 'act_fn': ReLU(), 'optimizer': 'Adadelta', 'dropout_prob': 0.1274695310346392, 'lr_mult': 4.13282303406362, 'patience': 64, 'initialization': 'Default'}
spotPython.fun.hyperlight 2024-01-07 23:07:14,003 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-07 23:07:49,342 DEBUG fun: train_model returned
spotPython.fun.hyperlight 2024-01-07 23:07:49,538 DEBUG 
config: {'l1': 32, 'epochs': 2048, 'batch_size': 32, 'act_fn': ReLU(), 'optimizer': 'Adadelta', 'dropout_prob': 0.2, 'lr_mult': 5.0, 'patience': 64, 'initialization': 'Default'}
spotPython.fun.hyperlight 2024-01-07 23:07:49,538 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-07 23:08:47,814 DEBUG fun: train_model returned
spotPython.fun.hyperlight 2024-01-07 23:08:47,990 DEBUG 
config: {'l1': 32, 'epochs': 1024, 'batch_size': 32, 'act_fn': ReLU(), 'optimizer': 'Adadelta', 'dropout_prob': 0.1860108088927697, 'lr_mult': 4.753789204999061, 'patience': 128, 'initialization': 'Default'}
spotPython.fun.hyperlight 2024-01-07 23:08:47,990 DEBUG fun: Calling train_model
spotPython.fun.hyperlight 2024-01-07 23:09:50,205 DEBUG fun: train_model returned
spotPython.fun.hyperlight 2024-01-07 23:09:50,262 DEBUG 
config: {'l1': 32, 'epochs': 1024, 'batch_size': 32, 'act_fn': ReLU(), 'optimizer': 'Adadelta', 'dropout_prob': 0.17688756271100078, 'lr_mult': 4.704058365229527, 'patience': 128, 'initialization': 'Default'}
spotPython.fun.hyperlight 2024-01-07 23:09:50,262 DEBUG fun: Calling train_model
